// Hello Java

/*
 * javac MyClass.java -> MyClass.class (compiler)
 * java MyClass (bytecode) (interpreter)
 *
 * Bytecode is a machine-independent code generated by the Java compiler and
 * executed by the interpreter
 *
 * Running a single-file program in one line
 * java MyFile.java
 */

 // Naming convention
 // MyClass, SuperStore -> classes, constructors, interfaces
 // myVariable, myMethod() -> variables and methods

public class HelloJava {
  public static void main(String[] args) {
    System.out.println("Hello Java");
  }
}
